### PR TITLE
Add ability to set Timezone in config

### PR DESCRIPTION
**Pull request by mikemand**
Using the `.env` file, we can change the timezone used for Twig.

I use Laravel Valet, and setting the timezone via `php.ini` does not work. But this does. 😀

### CODE REVIEW

**Comment by mikemand** [comment]
I _think_ I can replace both instances of `$twig->getEnvironment()->getExtension(CoreExtension::class)` with a variable, but I'm not 100% sure. I've never used Twig so I don't know if that works or not.

I also couldn't find any tests relating to the display of the date & time, so I was not sure where exactly to insert a test for this.

**Comment by PHLAK** [comment]
Fixed errors and merged manually.

Thank you for the PR!

**Comment by mikemand** [comment]
Thanks @PHLAK! Do you have a plan for when you'll do the next release?

**Comment by PHLAK** [comment]
I was just debating if I wanted to push this out as it's own update today @mikemand. I think I might.

**Comment by mikemand** [comment]
No rush. I will just be happy to finally not have to do math every time I have to check when a file was last updated, LOL.

**Comment by PHLAK** [comment]
Here you go: https://github.com/DirectoryLister/DirectoryLister/releases/tag/3.0.5

**Comment by mikemand** [comment]
You are the best! Thanks!

**Pull request closed without merging**
