### PR TITLE
Add column sorting

### PR DESCRIPTION
**Pull request by Tampa**
Sorting by date, filename and size is basic stuff that really should be in the base version. I forked from an already existing fork with that feature and made it work on my webspace. It would default to host/?dir instead of host/installdir/?dir, so I added that function to add that layer back. Should work properly now when installed in a subdirectory.

### CODE REVIEW

**Comment by PHLAK** [comment]
This is a great start, however can we change it to NOT reorder the  `..` directory? This should always be the top most listed directory.

image

**Comment by Tampa** [comment]
Okay I added a commit that should update the listDirectory function to remove the parent first and then add it back to the top before returning the array. I am not sure if this is an okay way of doing it, I am not that good with arrays.

**Comment by Tampa** [comment]
Decided to add directory sizes to the lists to see if folders get too large as I am uploading things constantly. Should work well on unix hosts, could add a windows version too(even though I think windows should not host sites). Thinking about adding previews or something to pictures perhaps.

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all pull requests opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and open a new PR if necessary.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).

**Comment by Tampa** [comment]
We'd have happily helped get something out sooner if you had bothered to say that you were working on something. Instead of bringing V2 to a nice closure adding the most requested features, some of which I spent days working on to get stuffed in there properly you just nuke it from orbit. I get you want to use the rep from the project to get the word out, but it still feels like a slap in the face. At least a bit of recognition of all the forks and work others have done to keep V2 alive for this long would have been nice.

**Comment by PHLAK** [comment]
Sorry @Tampa, I never meant to downplay the contributions of others and I appreciate each and every issue and PR opened.

**Comment by Tampa** [comment]
"Thanks to all those who over the months of my inactivity on the project have extended its functionality and added many features that were dearly requested to it. You helped bridge the gap between the versions and I dedicate this new version to all of you." Or something along those lines.

I personally really liked the 3 files and a folder structure V2 had, it was easy to deploy and the straight php code meant I could just change what bothered me the most. The various forks all fixed small stuff like unicode support, sorting, you name it. I tried my best to combine what I could into a single version that would close as many issue tickets. Had I known you were working on V3 I would probably have offered to help with some code or what I noticed may become problematic in running all those requested features at once in a production environment. I looked for a simple file listing system with enough features to feel close to what most file explorers on desktop had to offer and after I found this project I was quite happy to finally have something that was simple and extendable. I am not sure I grasp this new version and framework and whenever I hear that I always fear of bloat just because the framework has some concept that sounds appealing. So I hope you still plan to embrace what made this project big in the first place, the simple drop-in style and straight forward code that does not require a degree to comprehend and extend.

Anyways, good luck with V3, I will keep my V2 fork around and maybe work on it whenever needed, it works for me and currently has all the features I need. Maybe I even backport some stuff from V3 into it if I fancy myself something I see. :)

**Pull request closed without merging**
