### PR TITLE
Added Download Counter

### PR DESCRIPTION
**Pull request by veso266**
Hi there I have added Download Counter to default bootstrap theme (bootstrap_dc)
hope you like it, as I missed Download counter in Default DirectoryLister I added it

### CODE REVIEW

**Comment by Tampa** [comment]
Would love to merge this with my fork, this original version seems not maintained :/

**Comment by veso266** [comment]
@Tampa sure why not (although I don't yet know how to do that :smile: )
in the meantime I fixed some bugs and added Dark version and a switch to my theme: https://github.com/veso266/DirectoryLister if you want to take a look :smile:

**Comment by Tampa** [comment]
I can try to merge from your repo into mine or you can apply your changes to my repo and then open a merge request like this here to have it merged in. I attempted to make a download counter a while back along with some other statistics like the overall bandwidth used and most popular file ranking, but never got around to it, because I wanted to keep it compatible with Windows as well. I have since ditched that requirement though(Mainly cause Windows webservers are bad anyways).

**Comment by veso266** [comment]
did you only add this: https://github.com/Tampa/DirectoryLister/commit/a875db1b7144d4b6f08cb92663d3b0be81fc069d

since original Directory Lister, couze I only added Download Counter and my theme, left the rest intact

**Comment by Tampa** [comment]
What I meant was if you go to my repo and apply the changes you made to it and then send me a pull request I'll happily merge. I will try to merge your changes into mine at some point, but I cannot say when and I would want to go back to supporting all platforms again, not just linux, because the original was platform independent as well. If you want you can open an issue ticket on my repo requesting the addition of the download counter so I can track integration into my repo and have a clear line of feedback there. I plan to restructure the features so they are configurable and thus optional, from truly lightweight to more feature-rich, but that will take time and it would help to work together on this to keep it alive.(I'm also not the most experienced php developer either) :)

**Comment by sevospl** [comment]
What happened to it? It's not anymore available for some odd reason. Or perhaps I missed out smth?

**Comment by veso266** [comment]
Dont know
My is still there: https://github.com/veso266/DirectoryLister

**Pull request closed without merging**
